packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@astrojs/node': 9.4.6
  '@astrojs/react': 4.3.0
  '@csstools/postcss-global-data': 3.1.0
  '@rijkshuisstijl-community/components-css': 7.0.0
  '@rijkshuisstijl-community/components-react': 7.0.0
  '@rijkshuisstijl-community/design-tokens': 7.0.0
  '@types/react-dom': 19.1.6
  '@types/react': 19.1.8
  astro: 5.14.3
  clsx: 2.1.1
  i18next: 25.3.2
  openapi-fetch: 0.14.0
  openapi-typescript: 7.9.1
  postcss-custom-media: 11.0.6
  react-dom: 19.1.0
  react-markdown: 10.1.0
  react: 19.1.0
  typescript: 5.9.3
  vite: 7.1.5

catalogs: 
  react18: 
    react: '>=18.2.0'
    react-dom: '>=18.2.0'
    '@types/react': '>=18'
    '@types/react-dom': '>=18'
  react19: 
    react: '>=19.1.0'
    react-dom: '>=19.1.0'
    '@types/react': '>=19'
    '@types/react-dom': '>=19'
