packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@astrojs/node': 9.5.1
  '@astrojs/react': 4.4.2
  '@csstools/postcss-global-data': 3.1.0
  '@rijkshuisstijl-community/components-css': 8.0.0
  '@rijkshuisstijl-community/components-react': 7.0.0
  '@rijkshuisstijl-community/design-tokens': 8.0.0
  '@types/react-dom': 19.1.11
  '@types/react': 19.1.17
  astro: 5.16.5
  clsx: 2.1.1
  i18next: 25.7.1
  openapi-fetch: 0.15.0
  openapi-typescript: 7.10.1
  postcss-custom-media: 11.0.6
  react-dom: 19.1.4
  react-markdown: 10.1.0
  react: 19.1.4
  typescript: 5.9.3
  vite: 7.2.7

catalogs: 
  react18: 
    react: '18.2.0 <19.0.0'
    react-dom: '18.2.0'
    '@types/react': '>=18 <19'
    '@types/react-dom': '>=18 <19'
  react19: 
    react: '19.1.4'
    react-dom: '19.1.4'
    '@types/react': '>=19.1 <19.2'
    '@types/react-dom': '>=19.1 <19.2'
