packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  astro: 5.12.1
  '@astrojs/react': 4.3.0
  clsx: 2.1.1
  i18next: 25.5.3
  nanostores: 1.0.1
  '@nanostores/react': 1.0.0
  react: 19.1.0
  react-dom: 19.1.0
  react-markdown: 10.1.0
  '@rijkshuisstijl-community/components-css': 7.0.0
  '@rijkshuisstijl-community/components-react': 6.0.1
  '@rijkshuisstijl-community/design-tokens': 7.0.0
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  vite: 7.1.5
  openapi-typescript: 7.9.1
  openapi-fetch: 0.14.0

catalogs: 
  react18: 
    react: '>=18.2.0'
    react-dom: '>=18.2.0'
    '@types/react': '>=18'
    '@types/react-dom': '>=18'
  react19: 
    react: '>=19.1.0'
    react-dom: '>=19.1.0'
    '@types/react': '>=19'
    '@types/react-dom': '>=19'
