/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/git-organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List git organisations
         * @description Returns a list of git organisations that are included in the register.
         */
        get: operations["listGitOrganisations"];
        put?: never;
        /**
         * Create git organisation
         * @description Register a new git organisation in the register.
         */
        post: operations["createGitOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repositories
         * @description Returns a list of OSS repositories included in the register. Omit publiccode for all repositories, publiccode=true for repositories with a publiccode.yaml URL only, publiccode=false for repositories without a publiccode.yaml URL.
         */
        get: operations["listRepositories"];
        put?: never;
        /**
         * Create repository
         * @description Register a new OSS repository in the register.
         */
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get repository by id
         * @description Returns a single OSS repository by id.
         */
        get: operations["getRepositoryById"];
        /**
         * Specifieke repository updaten
         * @description Specifieke repository updaten
         */
        put: operations["updateRepository"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organisations
         * @description List organisations
         */
        get: operations["listOrganisations"];
        put?: never;
        /**
         * Create organisation
         * @description Create a new organisation.
         */
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/_search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search repositories
         * @description Returns a list of OSS repositories included in the register.
         */
        get: operations["searchRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listGitOrganisations: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                perPage?: number;
                /** @description Filter on organisation URI. */
                organisation?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    /** @description Links to the previous, next, last or first pages */
                    Link?: string;
                    /** @description Total number of items available */
                    "Total-Count"?: number;
                    /** @description Current page number */
                    "Current-Page"?: number;
                    /** @description Number of items per page */
                    "Per-Page"?: number;
                    /** @description Total number of pages available */
                    "Total-Pages"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        readonly id: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /**
                         * Git organisation URI
                         * Format: uri
                         * @description URL of the git organisation
                         * @example https://github.com/developer-overheid-nl
                         */
                        url: string;
                    }[];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    createGitOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Organisation URI
                     * Format: uri
                     * @description The unique identifier for an organisation
                     * @example https://developer.overheid.nl
                     */
                    organisationUri?: string;
                    /**
                     * Format: uri
                     * @description URL of the git organisation.
                     * @example https://github.com/developer-overheid-nl
                     */
                    url?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        readonly id: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /**
                         * Git organisation URI
                         * Format: uri
                         * @description URL of the git organisation
                         * @example https://github.com/developer-overheid-nl
                         */
                        url: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    listRepositories: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                perPage?: number;
                /** @description Filter on organisation URI. */
                organisation?: string;
                /** @description Filter on publiccode.yaml presence. true: only repositories with a publiccode.yaml URL, false: only repositories without a publiccode.yaml URL. Omit for all repositories. */
                publiccode?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    /** @description Links to the previous, next, last or first pages */
                    Link?: string;
                    /** @description Total number of items available */
                    "Total-Count"?: number;
                    /** @description Current page number */
                    "Current-Page"?: number;
                    /** @description Number of items per page */
                    "Per-Page"?: number;
                    /** @description Total number of pages available */
                    "Total-Pages"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        readonly id?: string;
                        /**
                         * Format: uri
                         * @description URL of the source code repository.
                         * @example https://github.com/developer-overheid-nl/don-site
                         */
                        url?: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation?: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /** @description URL of publiccode.yaml in the repository. */
                        publicCodeUrl?: string;
                        /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
                        shortDescription?: string;
                        /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
                        name?: string;
                        /** Format: date-time */
                        readonly createdAt?: string;
                        /** Format: date-time */
                        readonly lastCrawledAt?: string;
                        /** Format: date-time */
                        readonly lastActivityAt?: string;
                    }[];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the source code repository.
                     * @example https://github.com/developer-overheid-nl/don-site
                     */
                    url?: string;
                    /**
                     * Organisation URI
                     * Format: uri
                     * @description The unique identifier for an organisation
                     * @example https://developer.overheid.nl
                     */
                    organisationUri?: string;
                    /** @description URL of publiccode.yaml in the repository. */
                    publicCodeUrl?: string;
                    /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
                    shortDescription?: string;
                    /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
                    name?: string;
                    /** Format: date-time */
                    readonly createdAt?: string;
                    /** Format: date-time */
                    readonly lastCrawledAt?: string;
                    /** Format: date-time */
                    lastActivityAt?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        readonly id?: string;
                        /**
                         * Format: uri
                         * @description URL of the source code repository.
                         * @example https://github.com/developer-overheid-nl/don-site
                         */
                        url?: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation?: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /** @description URL of publiccode.yaml in the repository. */
                        publicCodeUrl?: string;
                        /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
                        shortDescription?: string;
                        /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
                        name?: string;
                        /** Format: date-time */
                        readonly createdAt?: string;
                        /** Format: date-time */
                        readonly lastCrawledAt?: string;
                        /** Format: date-time */
                        readonly lastActivityAt?: string;
                        /** @description Long description of the repository, typically from publiccode.yaml. */
                        longDescription?: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    getRepositoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        readonly id?: string;
                        /**
                         * Format: uri
                         * @description URL of the source code repository.
                         * @example https://github.com/developer-overheid-nl/don-site
                         */
                        url?: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation?: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /** @description URL of publiccode.yaml in the repository. */
                        publicCodeUrl?: string;
                        /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
                        shortDescription?: string;
                        /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
                        name?: string;
                        /** Format: date-time */
                        readonly createdAt?: string;
                        /** Format: date-time */
                        readonly lastCrawledAt?: string;
                        /** Format: date-time */
                        readonly lastActivityAt?: string;
                        /** @description Long description of the repository, typically from publiccode.yaml. */
                        longDescription?: string;
                    };
                };
            };
            /** @description Resource does not exist */
            404: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    updateRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the source code repository.
                     * @example https://github.com/developer-overheid-nl/don-site
                     */
                    url?: string;
                    /**
                     * Organisation URI
                     * Format: uri
                     * @description The unique identifier for an organisation
                     * @example https://developer.overheid.nl
                     */
                    organisationUri?: string;
                    /** @description URL of publiccode.yaml in the repository. */
                    publicCodeUrl?: string;
                    /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
                    shortDescription?: string;
                    /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
                    name?: string;
                    /** Format: date-time */
                    readonly createdAt?: string;
                    /** Format: date-time */
                    readonly lastCrawledAt?: string;
                    /** Format: date-time */
                    lastActivityAt?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        readonly id?: string;
                        /**
                         * Format: uri
                         * @description URL of the source code repository.
                         * @example https://github.com/developer-overheid-nl/don-site
                         */
                        url?: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation?: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /** @description URL of publiccode.yaml in the repository. */
                        publicCodeUrl?: string;
                        /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
                        shortDescription?: string;
                        /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
                        name?: string;
                        /** Format: date-time */
                        readonly createdAt?: string;
                        /** Format: date-time */
                        readonly lastCrawledAt?: string;
                        /** Format: date-time */
                        readonly lastActivityAt?: string;
                        /** @description Long description of the repository, typically from publiccode.yaml. */
                        longDescription?: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
            /** @description Resource does not exist */
            404: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    listOrganisations: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    /** @description Links to the previous, next, last or first pages */
                    Link?: string;
                    /** @description Total number of items available */
                    "Total-Count"?: number;
                    /** @description Current page number */
                    "Current-Page"?: number;
                    /** @description Number of items per page */
                    "Per-Page"?: number;
                    /** @description Total number of pages available */
                    "Total-Pages"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Organisation URI
                         * Format: uri
                         * @description The unique identifier for an organisation
                         * @example https://developer.overheid.nl
                         */
                        uri: string;
                        /**
                         * @description The label of the organisation
                         * @example developer.overheid.nl
                         */
                        label: string;
                    }[];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Organisation URI
                     * Format: uri
                     * @description The unique identifier for an organisation
                     * @example https://developer.overheid.nl
                     */
                    uri: string;
                    /**
                     * @description The label of the organisation
                     * @example developer.overheid.nl
                     */
                    label: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Organisation URI
                         * Format: uri
                         * @description The unique identifier for an organisation
                         * @example https://developer.overheid.nl
                         */
                        uri: string;
                        /**
                         * @description The label of the organisation
                         * @example developer.overheid.nl
                         */
                        label: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    searchRepositories: {
        parameters: {
            query: {
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                perPage?: number;
                /** @description Filter on organisation URI. */
                organisation?: string;
                /** @description Search term. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    /** @description Links to the previous, next, last or first pages */
                    Link?: string;
                    /** @description Total number of items available */
                    "Total-Count"?: number;
                    /** @description Current page number */
                    "Current-Page"?: number;
                    /** @description Number of items per page */
                    "Per-Page"?: number;
                    /** @description Total number of pages available */
                    "Total-Pages"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        readonly id?: string;
                        /**
                         * Format: uri
                         * @description URL of the source code repository.
                         * @example https://github.com/developer-overheid-nl/don-site
                         */
                        url?: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation?: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /** @description URL of publiccode.yaml in the repository. */
                        publicCodeUrl?: string;
                        /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
                        shortDescription?: string;
                        /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
                        name?: string;
                        /** Format: date-time */
                        readonly createdAt?: string;
                        /** Format: date-time */
                        readonly lastCrawledAt?: string;
                        /** Format: date-time */
                        readonly lastActivityAt?: string;
                    }[];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
}
export enum ApiPaths {
    listGitOrganisations = "/git-organisations",
    createGitOrganisation = "/git-organisations",
    listRepositories = "/repositories",
    createRepository = "/repositories",
    getRepositoryById = "/repositories/{id}",
    updateRepository = "/repositories/{id}",
    listOrganisations = "/organisations",
    createOrganisation = "/organisations",
    searchRepositories = "/repositories/_search"
}
