/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/git-organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List git organisations
         * @description Returns a list of git organisations that are included in the register.
         */
        get: operations["listGitOrganisations"];
        put?: never;
        /**
         * Create git organisation
         * @description Register a new git organisation in the register.
         */
        post: operations["createGitOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repository filter options
         * @description Returns all available filter options with counts per option. Counts are computed using faceted search: each filter group ignores its own active filter but applies all others, so counts always reflect realistic results.
         */
        get: operations["listRepositoryFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repositories
         * @description Returns a list of OSS repositories included in the register. Supports the same filter query parameters as the repository filter endpoint.
         */
        get: operations["listRepositories"];
        put?: never;
        /**
         * Create repository
         * @description Register a new OSS repository in the register.
         */
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Get repository by id
         * @description Returns a single OSS repository by id.
         */
        get: operations["getRepositoryById"];
        /**
         * Specifieke repository updaten
         * @description Specifieke repository updaten
         */
        put: operations["updateRepository"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organisations
         * @description List organisations
         */
        get: operations["listOrganisations"];
        put?: never;
        /**
         * Create organisation
         * @description Create a new organisation.
         */
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/_search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search repositories
         * @description Returns a list of OSS repositories included in the register.
         */
        get: operations["searchRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Problem JSON
         * @description Problem JSON schema representing errors and status code
         */
        ProblemJson: {
            /**
             * @description The HTTP status code generated by the origin server for this occurrence of the problem
             * @example 400
             */
            status: number;
            /**
             * @description A short, human-readable summary of the problem type
             * @example Request validation failed
             */
            title: string;
            errors?: {
                /**
                 * @description Location of the error (e.g., body, query, header)
                 * @enum {string}
                 */
                in: "body" | "query";
                /**
                 * @description Location in the document where the error occurred (JSON Pointer)
                 * @example #/foo[0]/bar
                 */
                location: string;
                /**
                 * @description A code representing the type of error
                 * @example date.format
                 */
                code: string;
                /**
                 * @description A detailed message describing the error
                 * @example must be ISO 8601
                 */
                detail: string;
            }[];
        };
        /** Format: uuid */
        ResourceUuid: string;
        /**
         * Organisation URI
         * Format: uri
         * @description The unique identifier for an organisation
         * @example https://developer.overheid.nl
         */
        OrganisationUri: string;
        /**
         * Git organisation URI
         * Format: uri
         * @description URL of the git organisation
         * @example https://github.com/developer-overheid-nl
         */
        GitOrganisationUrl: string;
        /**
         * Format: uri
         * @description URL of the source code repository.
         * @example https://github.com/developer-overheid-nl/don-site
         */
        RepositoryUrl: string;
        /** @description URL of publiccode.yaml in the repository. */
        PublicCodeUrl: string;
        /** @description Description of the repository from the git hosting (e.g. the repository description). Used as a fallback when no publiccode.yaml is available. */
        RepositoryShortDescription: string;
        /** @description Name of the repository from the git hosting. Used as a fallback when no publiccode.yaml is available. */
        RepositoryName: string;
        /** Format: date-time */
        CreatedAt: string;
        /** Format: date-time */
        LastCrawledAt: string;
        /** Format: date-time */
        LastActivityAt: string;
        /**
         * Organisation summary
         * @description An organisation from the catalog
         */
        OrganisationSummary: {
            uri: components["schemas"]["OrganisationUri"];
            /**
             * @description The label of the organisation
             * @example developer.overheid.nl
             */
            label: string;
        };
        /**
         * Git Organisation Input
         * @description A git organisation input for creating or updating a git organisation in the catalog
         */
        GitOrganisationInput: {
            organisationUri?: components["schemas"]["OrganisationUri"];
            url?: components["schemas"]["GitOrganisationUrl"];
        };
        /**
         * GitOrganisation
         * @description A git organisation from the catalog
         */
        GitOrganisation: {
            id: components["schemas"]["ResourceUuid"];
            organisation: components["schemas"]["OrganisationSummary"];
            url: components["schemas"]["GitOrganisationUrl"];
        };
        /**
         * Repository
         * @description An OSS repository from the catalog
         */
        RepositorySummary: {
            id?: components["schemas"]["ResourceUuid"];
            url?: components["schemas"]["RepositoryUrl"];
            /** @description Fork status supplied by the crawler based on the code hosting provider. */
            readonly isFork?: boolean;
            organisation?: components["schemas"]["OrganisationSummary"];
            publicCodeUrl?: components["schemas"]["PublicCodeUrl"];
            shortDescription?: components["schemas"]["RepositoryShortDescription"];
            name?: components["schemas"]["RepositoryName"];
            createdAt?: components["schemas"]["CreatedAt"];
            lastCrawledAt?: components["schemas"]["LastCrawledAt"];
            readonly lastActivityAt?: components["schemas"]["LastActivityAt"];
        };
        /**
         * Repository input
         * @description A repository input for creating or updating a repository in the catalog
         */
        RepositoryInput: {
            url?: components["schemas"]["RepositoryUrl"];
            organisationUri?: components["schemas"]["OrganisationUri"];
            publicCodeUrl?: components["schemas"]["PublicCodeUrl"];
            /** @description Fork status supplied by the crawler based on the code hosting provider. */
            isFork?: boolean;
            shortDescription?: components["schemas"]["RepositoryShortDescription"];
            name?: components["schemas"]["RepositoryName"];
            createdAt?: components["schemas"]["CreatedAt"];
            lastCrawledAt?: components["schemas"]["LastCrawledAt"];
            lastActivityAt?: components["schemas"]["LastActivityAt"];
        };
        /**
         * Repository detail
         * @description A detailed OSS repository from the catalog
         */
        RepositoryDetail: components["schemas"]["RepositorySummary"] & {
            publicCode?: components["schemas"]["PublicCode"];
            /** @description Long description of the repository, typically from publiccode.yaml. */
            longDescription?: string;
        };
        /** @description A single option within a multi-select filter group. */
        FilterOption: {
            /** @description The filter value to pass as a query parameter. */
            value: string;
            /** @description Human-readable label for the option. */
            label: string;
            /** @description Optional description of the filter value. */
            description?: string | null;
            /** @description Number of repositories matching this option, given the other active filters. */
            count: number;
            /** @description Whether this option is currently selected. */
            selected: boolean;
        };
        /** @description A filter group with metadata and available options or current value. */
        FilterGroup: {
            /**
             * @description Unique key of the filter group, matching the query parameter name.
             * @example softwareType
             */
            key: string;
            /** @description Human-readable label for the filter group. */
            label: string;
            /** @description Description of what this filter does. */
            description: string;
            /**
             * @description Filter type. toggle: on/off switch. date: date input (ISO 8601). multi-select: multiple values selectable. single-select: one value selectable from a list.
             * @enum {string}
             */
            type: "toggle" | "date" | "multi-select" | "single-select";
            /** @description Current filter value. For toggle: boolean true or false. For date: ISO 8601 date (yyyy-MM-dd). Not present for multi-select. */
            value?: boolean | string;
            /** @description For toggle filters, the number of repositories that would match when the toggle is enabled (value true), regardless of the current value. For date filters, the number of repositories matching the current date value; only present when a date is set. Not present for multi-select. */
            count?: number | null;
            /** @description Available options with counts. Only present for multi-select type. */
            options?: components["schemas"]["FilterOption"][];
        };
        /** @description Mandatory and conditionally mandatory fields extracted from publiccode.yml v0.5.0. */
        PublicCode: {
            /**
             * @description Version of the publiccode.yml schema.
             * @enum {string}
             */
            publiccodeYmlVersion: "0" | "0.2" | "0.2.0" | "0.2.1" | "0.2.2" | "0.3" | "0.3.0" | "0.4" | "0.4.0" | "0.5" | "0.5.0";
            /** @description Software name from publiccode.yml. */
            name: string;
            /**
             * Format: uri
             * @description Repository or project URL from publiccode.yml.
             */
            url: string;
            /** @description Supported platforms. */
            platforms: string[];
            /**
             * @description Development status from publiccode.yml.
             * @enum {string}
             */
            developmentStatus: "concept" | "development" | "beta" | "stable" | "obsolete";
            /**
             * @description Software type from publiccode.yml.
             * @enum {string}
             */
            softwareType: "standalone/mobile" | "standalone/iot" | "standalone/desktop" | "standalone/web" | "standalone/backend" | "standalone/other" | "addon" | "library" | "configurationFiles";
            legal: {
                /** @description SPDX license expression. */
                license: string;
            };
            /** @description Localized description blocks keyed by language tag. */
            description: {
                [key: string]: {
                    shortDescription: string;
                    longDescription?: string;
                    features?: string[];
                };
            };
            /** @description This section provides information on the maintenance status of the software, useful to evaluate whether the software is actively developed or not. */
            maintenance: {
                /** @enum {string} */
                type: "internal" | "contract" | "community" | "none";
                contacts?: {
                    name: string;
                }[];
                contractors?: {
                    name: string;
                    /** Format: date */
                    until: string;
                }[];
            };
            localisation: {
                localisationReady: boolean;
                availableLanguages: string[];
            };
            organisation?: {
                uri: components["schemas"]["OrganisationUri"];
            };
            dependsOn?: {
                open?: {
                    name: string;
                }[];
                proprietary?: {
                    name: string;
                }[];
                hardware?: {
                    name: string;
                }[];
            };
            fundedBy?: {
                name?: string;
            }[];
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                "API-Version": components["headers"]["APIVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemJson"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                "API-Version": components["headers"]["APIVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemJson"];
            };
        };
    };
    parameters: {
        /** @description Page number (1-based). */
        Page: number;
        /** @description Number of results per page. */
        PerPage: number;
        /** @description Filter by organisation URI. */
        OrganisationFilter: string;
        /** @description Filter on publiccode.yaml presence. true: only repositories with a publiccode.yaml URL. Omit or set false for all repositories. */
        PublicCodeFilter: boolean;
        /** @description Filter by last activity date. Format: ISO 8601 (yyyy-MM-dd). */
        LastActivityAfterFilter: string;
        /** @description Filter by software type. Repeatable for multiple values. */
        SoftwareTypeFilter: string[];
        /** @description Filter by development status. Repeatable for multiple values. */
        DevelopmentStatusFilter: string[];
        /** @description Filter by maintenance type. Repeatable for multiple values. */
        MaintenanceTypeFilter: string[];
        /** @description Filter by platform. Repeatable for multiple values. */
        PlatformsFilter: string[];
        /** @description Filter by available language (ISO 639-1). Repeatable for multiple values. */
        AvailableLanguagesFilter: string[];
        /** @description Filter by license (SPDX identifier). Repeatable for multiple values. */
        LicenseFilter: string[];
        /** @description Unique identifier of the resource. */
        ResourceId: string;
        /** @description Search term. */
        SearchQuery: string;
    };
    requestBodies: never;
    headers: {
        /** @description Semver of this API */
        APIVersion: string;
        /** @description Links to the previous, next, last or first pages */
        Link: string;
        /** @description Total number of items available */
        TotalCount: number;
        /** @description Current page number */
        CurrentPage: number;
        /** @description Number of items per page */
        PerPage: number;
        /** @description Total number of pages available */
        TotalPages: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listGitOrganisations: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
                /** @description Filter by organisation URI. */
                organisation?: components["parameters"]["OrganisationFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitOrganisation"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createGitOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitOrganisationInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitOrganisation"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listRepositoryFilters: {
        parameters: {
            query?: {
                /** @description Filter by organisation URI. */
                organisation?: components["parameters"]["OrganisationFilter"];
                /** @description Filter on publiccode.yaml presence. true: only repositories with a publiccode.yaml URL. Omit or set false for all repositories. */
                publiccode?: components["parameters"]["PublicCodeFilter"];
                /** @description Filter by last activity date. Format: ISO 8601 (yyyy-MM-dd). */
                lastActivityAfter?: components["parameters"]["LastActivityAfterFilter"];
                /** @description Filter by software type. Repeatable for multiple values. */
                softwareType?: components["parameters"]["SoftwareTypeFilter"];
                /** @description Filter by development status. Repeatable for multiple values. */
                developmentStatus?: components["parameters"]["DevelopmentStatusFilter"];
                /** @description Filter by maintenance type. Repeatable for multiple values. */
                maintenanceType?: components["parameters"]["MaintenanceTypeFilter"];
                /** @description Filter by platform. Repeatable for multiple values. */
                platforms?: components["parameters"]["PlatformsFilter"];
                /** @description Filter by available language (ISO 639-1). Repeatable for multiple values. */
                availableLanguages?: components["parameters"]["AvailableLanguagesFilter"];
                /** @description Filter by license (SPDX identifier). Repeatable for multiple values. */
                license?: components["parameters"]["LicenseFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterGroup"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listRepositories: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
                /** @description Filter by organisation URI. */
                organisation?: components["parameters"]["OrganisationFilter"];
                /** @description Filter on publiccode.yaml presence. true: only repositories with a publiccode.yaml URL. Omit or set false for all repositories. */
                publiccode?: components["parameters"]["PublicCodeFilter"];
                /** @description Filter by last activity date. Format: ISO 8601 (yyyy-MM-dd). */
                lastActivityAfter?: components["parameters"]["LastActivityAfterFilter"];
                /** @description Filter by software type. Repeatable for multiple values. */
                softwareType?: components["parameters"]["SoftwareTypeFilter"];
                /** @description Filter by development status. Repeatable for multiple values. */
                developmentStatus?: components["parameters"]["DevelopmentStatusFilter"];
                /** @description Filter by maintenance type. Repeatable for multiple values. */
                maintenanceType?: components["parameters"]["MaintenanceTypeFilter"];
                /** @description Filter by platform. Repeatable for multiple values. */
                platforms?: components["parameters"]["PlatformsFilter"];
                /** @description Filter by available language (ISO 639-1). Repeatable for multiple values. */
                availableLanguages?: components["parameters"]["AvailableLanguagesFilter"];
                /** @description Filter by license (SPDX identifier). Repeatable for multiple values. */
                license?: components["parameters"]["LicenseFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositorySummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRepositoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RepositoryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listOrganisations: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OrganisationSummary"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    searchRepositories: {
        parameters: {
            query: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
                /** @description Filter by organisation URI. */
                organisation?: components["parameters"]["OrganisationFilter"];
                /** @description Search term. */
                q: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositorySummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
export enum ApiPaths {
    listGitOrganisations = "/git-organisations",
    createGitOrganisation = "/git-organisations",
    listRepositoryFilters = "/repositories/filters",
    listRepositories = "/repositories",
    createRepository = "/repositories",
    getRepositoryById = "/repositories/{id}",
    updateRepository = "/repositories/{id}",
    listOrganisations = "/organisations",
    createOrganisation = "/organisations",
    searchRepositories = "/repositories/_search"
}
