/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List schemas
         * @description Returns a list of JSON Schemas included in the register. Supports the same filter query parameters as the schema filter endpoint.
         */
        get: operations["listSchemas"];
        put?: never;
        /**
         * Create schema
         * @description Register a new JSON Schema in the register. The schema is fetched from schemaUrl (or read from schemaBody), validated and stored together with derived metadata (title, description, dialect, root type and a content hash).
         */
        post: operations["createSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List schema filters
         * @description Returns all available filter options with counts. Counts are calculated based on the active filters and the optional search term q.
         */
        get: operations["listSchemaFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get schema by id
         * @description Returns a single JSON Schema based on its id, including the stored schema content.
         */
        get: operations["getSchemaById"];
        /**
         * Update schema
         * @description Re-fetches the JSON Schema from schemaUrl (or reads it from schemaBody) and updates the registered schema. The organisationUri must match the owner of the schema.
         */
        put: operations["updateSchema"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/{id}/schema.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get raw schema content
         * @description Returns the raw stored JSON Schema document.
         */
        get: operations["getSchemaContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organisations
         * @description List organisations
         */
        get: operations["listOrganisations"];
        put?: never;
        /**
         * Create organisation
         * @description Create a new organisation.
         */
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Problem JSON
         * @description Problem JSON schema representing errors and status code
         */
        ProblemJson: {
            /**
             * @description The HTTP status code generated by the origin server for this occurrence of the problem
             * @example 400
             */
            status: number;
            /**
             * @description A short, human-readable summary of the problem type
             * @example Request validation failed
             */
            title: string;
            errors?: {
                /**
                 * @description Location of the error (e.g., body, query, header)
                 * @enum {string}
                 */
                in: "body" | "query";
                /**
                 * @description Location in the document where the error occurred (JSON Pointer)
                 * @example #/foo[0]/bar
                 */
                location: string;
                /**
                 * @description A code representing the type of error
                 * @example date.format
                 */
                code: string;
                /**
                 * @description A detailed message describing the error
                 * @example must be ISO 8601
                 */
                detail: string;
            }[];
        };
        /**
         * @description Unique identifier of the schema
         * @example demo-bier
         */
        ResourceId: string;
        /**
         * Organisation URI
         * Format: uri
         * @description The unique identifier for an organisation
         * @example https://developer.overheid.nl
         */
        OrganisationUri: string;
        /**
         * Format: uri
         * @description Location of the JSON Schema document
         * @example https://schemas.example.org/Bier.schema.json
         */
        SchemaUrl: string;
        /**
         * @description Title of the JSON Schema (taken from the schema's title keyword)
         * @example Bier
         */
        SchemaTitle: string;
        /**
         * @description Description of the JSON Schema (taken from the schema's description keyword)
         * @example Het specifieke bier dat een brouwerij produceert
         */
        SchemaDescription: string;
        /**
         * @description Normalised JSON Schema dialect, derived from the $schema keyword
         * @example 2020-12
         * @enum {string}
         */
        SchemaDialect: "2020-12" | "2019-09" | "draft-07" | "draft-06" | "draft-04" | "oas-3.1" | "unknown";
        /**
         * @description Root type of the JSON Schema, derived from the top-level type keyword
         * @example object
         * @enum {string}
         */
        SchemaRootType: "object" | "array" | "string" | "number" | "integer" | "boolean" | "null" | "unknown";
        /**
         * @description Optional collection the schema belongs to
         * @example demo
         */
        SchemaCollection: string;
        /** Format: date-time */
        CreatedAt: string;
        /** Format: date-time */
        LastCrawledAt: string;
        /**
         * Organisation summary
         * @description An organisation from the catalog
         */
        OrganisationSummary: {
            uri: components["schemas"]["OrganisationUri"];
            /**
             * @description The label of the organisation
             * @example developer.overheid.nl
             */
            label: string;
        };
        /** @description Contact information of the schema maintainer */
        Contact: {
            /** @example Team developer.overheid.nl */
            name: string;
            /**
             * Format: email
             * @example developer.overheid@geonovum.nl
             */
            email?: string;
            /**
             * Format: uri
             * @example https://developer.overheid.nl
             */
            url?: string;
        };
        SchemaSummary: {
            id: components["schemas"]["ResourceId"];
            schemaUrl?: components["schemas"]["SchemaUrl"];
            title: components["schemas"]["SchemaTitle"];
            description?: components["schemas"]["SchemaDescription"];
            dialect?: components["schemas"]["SchemaDialect"];
            rootType?: components["schemas"]["SchemaRootType"];
            collection?: components["schemas"]["SchemaCollection"];
            contact?: components["schemas"]["Contact"];
            organisation?: components["schemas"]["OrganisationSummary"];
            createdAt?: components["schemas"]["CreatedAt"];
            lastCrawledAt?: components["schemas"]["LastCrawledAt"];
            /** @description Name reported by the SourceMeta One API entry */
            sourceMetaName?: string;
            /**
             * Format: uri
             * @description Identifier reported by the SourceMeta One API entry
             */
            sourceMetaIdentifier?: string;
            /** @description Original schema size in bytes reported by SourceMeta */
            sourceMetaBytes?: number;
            /** @description Bundled schema size in bytes reported by SourceMeta */
            sourceMetaBytesBundled?: number;
            /** @description Base dialect reported by SourceMeta */
            sourceMetaBaseDialect?: string;
            /** @description Dialect reported by SourceMeta */
            sourceMetaDialect?: string;
            /** @description Health score reported by SourceMeta */
            sourceMetaHealth?: number;
            /** @description Number of dependencies reported by SourceMeta */
            sourceMetaDependencies?: number;
        };
        SchemaDetail: components["schemas"]["SchemaSummary"] & {
            /** @description The stored JSON Schema document */
            content?: Record<string, never>;
        };
        /** @description Register a JSON Schema by URL or by providing the schema body directly. Either schemaUrl or schemaBody is required. */
        SchemaPost: {
            id?: components["schemas"]["ResourceId"];
            schemaUrl?: components["schemas"]["SchemaUrl"];
            /** @description The JSON Schema document itself, as a JSON string. Required when schemaUrl is omitted. */
            schemaBody?: string;
            organisationUri: components["schemas"]["OrganisationUri"];
            contact: components["schemas"]["Contact"];
        };
        /** @description A single option within a multi-select filter group. */
        FilterOption: {
            /** @description The filter value to pass as a query parameter. */
            value: string;
            /** @description Human-readable label for the option. */
            label: string;
            /** @description Optional description of the filter value. */
            description?: string | null;
            /** @description Number of repositories matching this option, given the other active filters. */
            count: number;
            /** @description Whether this option is currently selected. */
            selected: boolean;
        };
        /** @description A filter group with metadata and available options or current value. */
        FilterGroup: {
            /**
             * @description Unique key of the filter group, matching the query parameter name.
             * @example softwareType
             */
            key: string;
            /** @description Human-readable label for the filter group. */
            label: string;
            /** @description Description of what this filter does. */
            description: string;
            /**
             * @description Filter type. toggle: on/off switch. date: date input (ISO 8601). multi-select: multiple values selectable. single-select: one value selectable from a list.
             * @enum {string}
             */
            type: "toggle" | "date" | "multi-select" | "single-select";
            /** @description Current filter value. For toggle: boolean true or false. For date: ISO 8601 date (yyyy-MM-dd). Not present for multi-select. */
            value?: boolean | string;
            /** @description For toggle filters, the number of repositories with the toggle condition available. For date filters, the number of repositories matching the current date value; only present when a date is set. Not present for multi-select. */
            count?: number | null;
            /** @description Available options with counts. Only present for multi-select type. */
            options?: components["schemas"]["FilterOption"][];
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                "API-Version": components["headers"]["APIVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemJson"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                "API-Version": components["headers"]["APIVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemJson"];
            };
        };
    };
    parameters: {
        /** @description Page number (1-based). */
        Page: number;
        /** @description Number of results per page. */
        PerPage: number;
        /** @description Search term to combine with repository filters. Matches repository name, short description, long description, publiccode.yml url and publiccode.yml landingURL. */
        SearchFilter: string;
        /** @description Filter by organisation URI. */
        OrganisationFilter: string;
        /** @description Filter schemas by JSON Schema dialect. Repeat the parameter to filter on multiple dialects. */
        DialectFilter: components["schemas"]["SchemaDialect"][];
        /** @description Filter schemas by root type. Repeat the parameter to filter on multiple root types. */
        RootTypeFilter: components["schemas"]["SchemaRootType"][];
        /** @description Unique identifier of the schema */
        ResourceId: components["schemas"]["ResourceId"];
    };
    requestBodies: never;
    headers: {
        /** @description Semver of this API */
        APIVersion: string;
        /** @description Links to the previous, next, last or first pages */
        Link: string;
        /** @description Total number of items available */
        TotalCount: number;
        /** @description Current page number */
        CurrentPage: number;
        /** @description Number of items per page */
        PerPage: number;
        /** @description Total number of pages available */
        TotalPages: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSchemas: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
                /** @description Search term to combine with repository filters. Matches repository name, short description, long description, publiccode.yml url and publiccode.yml landingURL. */
                q?: components["parameters"]["SearchFilter"];
                /** @description Filter by organisation URI. */
                organisation?: components["parameters"]["OrganisationFilter"];
                /** @description Filter schemas by JSON Schema dialect. Repeat the parameter to filter on multiple dialects. */
                dialect?: components["parameters"]["DialectFilter"];
                /** @description Filter schemas by root type. Repeat the parameter to filter on multiple root types. */
                rootType?: components["parameters"]["RootTypeFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaPost"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listSchemaFilters: {
        parameters: {
            query?: {
                /** @description Search term to combine with repository filters. Matches repository name, short description, long description, publiccode.yml url and publiccode.yml landingURL. */
                q?: components["parameters"]["SearchFilter"];
                /** @description Filter by organisation URI. */
                organisation?: components["parameters"]["OrganisationFilter"];
                /** @description Filter schemas by JSON Schema dialect. Repeat the parameter to filter on multiple dialects. */
                dialect?: components["parameters"]["DialectFilter"];
                /** @description Filter schemas by root type. Repeat the parameter to filter on multiple root types. */
                rootType?: components["parameters"]["RootTypeFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterGroup"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSchemaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the schema */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the schema */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaPost"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getSchemaContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the schema */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/schema+json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listOrganisations: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OrganisationSummary"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "API-Version": components["headers"]["APIVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
export enum ApiPaths {
    listSchemas = "/schemas",
    createSchema = "/schemas",
    listSchemaFilters = "/schemas/filters",
    getSchemaById = "/schemas/{id}",
    updateSchema = "/schemas/{id}",
    getSchemaContent = "/schemas/{id}/schema.json",
    listOrganisations = "/organisations",
    createOrganisation = "/organisations"
}
