/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alle API's ophalen
         * @description Alle API's ophalen
         */
        get: operations["listApis"];
        put?: never;
        /**
         * Registreer een nieuwe API met een OpenAPI URL
         * @description Registreer een nieuwe API met een OpenAPI URL
         */
        post: operations["createApi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Specifieke API ophalen
         * @description Specifieke API ophalen
         */
        get: operations["retreiveApi"];
        /**
         * Specifieke API updaten
         * @description Specifieke API updaten
         */
        put: operations["updateApi"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alle organisaties ophalen
         * @description Alle organisaties ophalen
         */
        get: operations["listOrganisations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Contact: {
            /**
             * Format: email
             * @example developer.overheid@geonovum.nl
             */
            email: string;
            /** @example Team developer.overheid.nl */
            name: string;
            /**
             * Format: uri
             * @example https://github.com/developer-overheid-nl/don-api-register/issues
             */
            url: string;
        };
        ApiDetail: components["schemas"]["ApiSummary"] & {
            auth?: string[] | null;
            description?: string;
            /**
             * Format: uri
             * @example https://apis.developer.overheid.nl/apis/3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            docsUri?: string;
            servers?: components["schemas"]["Server"][];
        };
        ApiSummary: WithRequired<components["schemas"]["ApiPost"], "contact"> & {
            /** @example API register API v1 */
            title: string;
            /** @example API van het API register (apis.developer.overheid.nl) */
            description?: string;
            organisation: components["schemas"]["Organisation"];
            /**
             * Format: int32
             * @default null
             */
            adrScore: number | null;
            lifecycle?: {
                /** @enum {string} */
                status?: "active" | "deprecated" | "sunset";
                /** @example 1.0.0 */
                version?: string;
            };
            _links?: {
                self?: {
                    /**
                     * Format: uri
                     * @example https://api.developer.overheid.nl/v1/apis/90szfOzDg
                     */
                    href?: string;
                };
            };
        };
        Server: {
            /**
             * Format: uri
             * @example https://api.developer.overheid.nl/v1
             */
            url: string;
            /** @example Production */
            description: string;
        };
        ApiPost: {
            /** @example 90szfOzDg */
            readonly id: string;
            /**
             * Format: uri
             * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
             */
            oasUrl?: string;
            /** @description Inline OpenAPI spec (JSON of YAML) */
            oasBody?: string;
            /**
             * Format: uri
             * @example https://api.developer.overheid.nl/api-register/v1/arazzo.yaml
             */
            arazzoUrl?: string;
            /** @description Inline Arazzo spec (JSON of YAML) */
            arazzoBody?: string;
            /**
             * Format: uri
             * @example https://identifier.overheid.nl/tooi/id/gemeente/gm0363
             */
            organisationUri: string;
            contact?: components["schemas"]["Contact"];
        } | unknown | unknown;
        Organisation: {
            /** @example Binnenlandse Zaken en Koninkrijksrelaties (BZK) */
            label: string;
            /**
             * Format: uri
             * @example https://identifier.overheid.nl/tooi/id/ministerie/mnre1034
             */
            uri: string;
            _links?: {
                apis?: {
                    /** @example /v1/apis?organisation=https://identifier.overheid.nl/tooi/id/ministerie/mnre1034 */
                    href?: string;
                };
            };
        };
    };
    responses: {
        /** @description Bad request */
        400: {
            headers: {
                "API-Version": components["headers"]["headers-API-Version"];
                Link: components["headers"]["Link"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /** @example Request validation failed */
                    title?: string;
                    invalidParams?: {
                        /** @example url */
                        name?: string;
                        /** @example Invalid URI format */
                        reason?: string;
                    };
                };
            };
        };
        /** @description Resource does not exist */
        404: {
            headers: {
                "API-Version": components["headers"]["headers-API-Version"];
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description De API-versie van de response */
        "API-Version": string;
        /** @description Semver of this API */
        "headers-API-Version": string;
        /** @description Links to the previous, next, last or first pages */
        Link: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["API-Version"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSummary"][];
                };
            };
        };
    };
    createApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiPost"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSummary"];
                };
            };
            400: components["responses"]["400"];
        };
    };
    retreiveApi: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiDetail"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    updateApi: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiPost"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSummary"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
        };
    };
    listOrganisations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["API-Version"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organisations?: components["schemas"]["Organisation"][];
                    };
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
