/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all APIs
         * @description List all APIs
         */
        get: operations["listApis"];
        put?: never;
        /**
         * Register a new API
         * @description Register a new API
         */
        post: operations["createApi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/_search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search apis
         * @description Returns a list of repositories matching the search query.
         */
        get: operations["searchApis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Retrieve a specific API
         * @description Retrieve a specific API
         */
        get: operations["retreiveApi"];
        /**
         * Update a specific API
         * @description Update a specific API
         */
        put: operations["updateApi"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}/postman": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Download Postman collection
         * @description Returns the generated Postman JSON.
         */
        get: operations["getPostman"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}/oas/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
                /** @description OAS version and format, e.g. 3.0.json or 3.1.yaml. */
                version: string;
            };
            cookie?: never;
        };
        /**
         * Download OAS document
         * @description Returns the OAS 3.0 or 3.1 specification in JSON or YAML.
         */
        get: operations["getOasVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI documentation
         * @description Download the OpenAPI specification for this API.
         */
        get: operations["getOpenApiSpecification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all organisations
         * @description List all organisations
         */
        get: operations["listOrganisations"];
        put?: never;
        /**
         * Create organisation
         * @description Create a new organisation.
         */
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get APIs with adoption status
         * @description Returns list of APIs with their compliance status
         */
        get: operations["getAdoptionApis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get adoption per rule
         * @description Returns adoption rate per ADR rule
         */
        get: operations["getAdoptionRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get adoption summary
         * @description Returns overall adoption KPIs for the selected period
         */
        get: operations["getAdoptionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get adoption timeline
         * @description Returns adoption over time for charts
         */
        get: operations["getAdoptionTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ModelsAdoptionApis: {
            adrVersion?: string;
            apis?: components["schemas"]["ModelsApiAdoption"][];
            period?: components["schemas"]["ModelsPeriod"];
        };
        ModelsAdoptionRules: {
            adrVersion?: string;
            period?: components["schemas"]["ModelsPeriod"];
            rules?: components["schemas"]["ModelsRuleAdoption"][];
            /** Format: int32 */
            totalApis?: number;
        };
        ModelsAdoptionSummary: {
            adrVersion?: string;
            /** Format: int32 */
            compliantApis?: number;
            /** Format: double */
            overallAdoptionRate?: number;
            period?: components["schemas"]["ModelsPeriod"];
            /** Format: int32 */
            totalApis?: number;
            /** Format: int32 */
            totalLintRuns?: number;
        };
        ModelsAdoptionTimeline: {
            adrVersion?: string;
            granularity?: string;
            series?: components["schemas"]["ModelsTimelineSeries"][];
        };
        ModelsApiAdoption: {
            apiId?: string;
            apiTitle?: string;
            isCompliant?: boolean;
            /** Format: date-time */
            lastLintDate?: string;
            organisation?: string;
            /** Format: int32 */
            totalViolations?: number;
            /** Format: int32 */
            totalWarnings?: number;
            violatedRules?: string[];
        };
        ModelsPeriod: {
            end?: string;
            start?: string;
        };
        ModelsRuleAdoption: {
            /** Format: double */
            adoptionRate?: number;
            code?: string;
            /** Format: int32 */
            compliantApis?: number;
            severity?: string;
            /** Format: int32 */
            violatingApis?: number;
        };
        ModelsTimelinePoint: {
            /** Format: double */
            adoptionRate?: number;
            /** Format: int32 */
            compliantApis?: number;
            period?: string;
            /** Format: int32 */
            totalApis?: number;
        };
        ModelsTimelineSeries: {
            dataPoints?: components["schemas"]["ModelsTimelinePoint"][];
            ruleCode?: string;
            type?: string;
        };
    };
    responses: {
        /** @description Bad request */
        400: {
            headers: {
                /** @description Semver of this API */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * @description The HTTP status code generated by the origin server for this occurrence of the problem
                     * @example 400
                     */
                    status: number;
                    /**
                     * @description A short, human-readable summary of the problem type
                     * @example Request validation failed
                     */
                    title: string;
                    errors?: {
                        /**
                         * @description Location of the error (e.g., body, query, header)
                         * @enum {string}
                         */
                        in: "body" | "query";
                        /**
                         * @description Location in the document where the error occurred (JSON Pointer)
                         * @example #/foo[0]/bar
                         */
                        location: string;
                        /**
                         * @description A code representing the type of error
                         * @example date.format
                         */
                        code: string;
                        /**
                         * @description A detailed message describing the error
                         * @example must be ISO 8601
                         */
                        detail: string;
                    }[];
                };
            };
        };
        /** @description Resource does not exist */
        404: {
            headers: {
                /** @description Semver of this API */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * @description The HTTP status code generated by the origin server for this occurrence of the problem
                     * @example 400
                     */
                    status: number;
                    /**
                     * @description A short, human-readable summary of the problem type
                     * @example Request validation failed
                     */
                    title: string;
                    errors?: {
                        /**
                         * @description Location of the error (e.g., body, query, header)
                         * @enum {string}
                         */
                        in: "body" | "query";
                        /**
                         * @description Location in the document where the error occurred (JSON Pointer)
                         * @example #/foo[0]/bar
                         */
                        location: string;
                        /**
                         * @description A code representing the type of error
                         * @example date.format
                         */
                        code: string;
                        /**
                         * @description A detailed message describing the error
                         * @example must be ISO 8601
                         */
                        detail: string;
                    }[];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApis: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                perPage?: number;
                /** @description Filter on organisation URI. */
                organisation?: string;
                /** @description Comma-separated list of API IDs. */
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    /** @description Links to the previous, next, last or first pages */
                    Link?: string;
                    /** @description Total number of items available */
                    "Total-Count"?: number;
                    /** @description Current page number */
                    "Current-Page"?: number;
                    /** @description Number of items per page */
                    "Per-Page"?: number;
                    /** @description Total number of pages available */
                    "Total-Pages"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The unique identifier for an API
                         * @example dicF0B3HR
                         */
                        readonly id: string;
                        /**
                         * Contact
                         * @description Contact details
                         */
                        contact: {
                            /**
                             * Format: email
                             * @description The email address of the contact
                             * @example developer.overheid@geonovum.nl
                             */
                            email: string;
                            /**
                             * @description The name of the contact
                             * @example Developer Overheid
                             */
                            name: string;
                            /**
                             * Format: uri
                             * @description The URL of the contact
                             * @example https://developer.overheid.nl
                             */
                            url: string;
                        };
                        /**
                         * @description The title of the API
                         * @example API register API v1
                         */
                        title: string;
                        /**
                         * @description The description of the API
                         * @example This is version 1 of the API register. This description can also contain Markdown.
                         */
                        description: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /**
                         * @description The ADR score of the API
                         * @example 85
                         */
                        adrScore: number | null;
                        /**
                         * Lifecycle
                         * @description The lifecycle status of the API
                         */
                        lifecycle: {
                            /**
                             * @description The lifecycle status
                             * @example deprecated
                             * @example sunset
                             * @example retired
                             * @enum {string}
                             */
                            status: "active" | "deprecated" | "sunset" | "retired";
                            /**
                             * @description The version of the API
                             * @example 1.0.0
                             */
                            version: string;
                            /**
                             * Format: date
                             * @description The date from which the lifecycle status is/has been deprecated, sunset or retired.
                             * @example 2025-01-15
                             */
                            from?: string | null;
                        };
                    }[];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    createApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * OAS Url
                     * Format: uri
                     * @description The URL of the OAS document
                     * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
                     */
                    oasUrl: string;
                    /**
                     * Organisation URI
                     * Format: uri
                     * @description The unique identifier for an organisation
                     * @example https://developer.overheid.nl
                     */
                    organisationUri: string;
                    /**
                     * Contact
                     * @description Contact details
                     */
                    contact?: {
                        /**
                         * Format: email
                         * @description The email address of the contact
                         * @example developer.overheid@geonovum.nl
                         */
                        email: string;
                        /**
                         * @description The name of the contact
                         * @example Developer Overheid
                         */
                        name: string;
                        /**
                         * Format: uri
                         * @description The URL of the contact
                         * @example https://developer.overheid.nl
                         */
                        url: string;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The unique identifier for an API
                         * @example dicF0B3HR
                         */
                        readonly id: string;
                        /**
                         * Contact
                         * @description Contact details
                         */
                        contact: {
                            /**
                             * Format: email
                             * @description The email address of the contact
                             * @example developer.overheid@geonovum.nl
                             */
                            email: string;
                            /**
                             * @description The name of the contact
                             * @example Developer Overheid
                             */
                            name: string;
                            /**
                             * Format: uri
                             * @description The URL of the contact
                             * @example https://developer.overheid.nl
                             */
                            url: string;
                        };
                        /**
                         * @description The title of the API
                         * @example API register API v1
                         */
                        title: string;
                        /**
                         * @description The description of the API
                         * @example This is version 1 of the API register. This description can also contain Markdown.
                         */
                        description: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /**
                         * @description The ADR score of the API
                         * @example 85
                         */
                        adrScore: number | null;
                        /**
                         * Lifecycle
                         * @description The lifecycle status of the API
                         */
                        lifecycle: {
                            /**
                             * @description The lifecycle status
                             * @example deprecated
                             * @example sunset
                             * @example retired
                             * @enum {string}
                             */
                            status: "active" | "deprecated" | "sunset" | "retired";
                            /**
                             * @description The version of the API
                             * @example 1.0.0
                             */
                            version: string;
                            /**
                             * Format: date
                             * @description The date from which the lifecycle status is/has been deprecated, sunset or retired.
                             * @example 2025-01-15
                             */
                            from?: string | null;
                        };
                    } & {
                        /**
                         * Format: uri
                         * @description The URL of the OAS document
                         * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
                         */
                        oasUrl: string | null;
                        /** @description The authentication methods supported by the API */
                        auth: string[];
                        /**
                         * Format: uri
                         * @description The URL to the documentation of the API
                         * @example https://developer.overheid.nl/kennisbank/
                         */
                        docsUrl: string | null;
                        servers: unknown;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    searchApis: {
        parameters: {
            query: {
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page. */
                perPage?: number;
                /** @description Filter on organisation URI. */
                organisation?: string;
                /** @description Search term. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    /** @description Links to the previous, next, last or first pages */
                    Link?: string;
                    /** @description Total number of items available */
                    "Total-Count"?: number;
                    /** @description Current page number */
                    "Current-Page"?: number;
                    /** @description Number of items per page */
                    "Per-Page"?: number;
                    /** @description Total number of pages available */
                    "Total-Pages"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The unique identifier for an API
                         * @example dicF0B3HR
                         */
                        readonly id: string;
                        /**
                         * Contact
                         * @description Contact details
                         */
                        contact: {
                            /**
                             * Format: email
                             * @description The email address of the contact
                             * @example developer.overheid@geonovum.nl
                             */
                            email: string;
                            /**
                             * @description The name of the contact
                             * @example Developer Overheid
                             */
                            name: string;
                            /**
                             * Format: uri
                             * @description The URL of the contact
                             * @example https://developer.overheid.nl
                             */
                            url: string;
                        };
                        /**
                         * @description The title of the API
                         * @example API register API v1
                         */
                        title: string;
                        /**
                         * @description The description of the API
                         * @example This is version 1 of the API register. This description can also contain Markdown.
                         */
                        description: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /**
                         * @description The ADR score of the API
                         * @example 85
                         */
                        adrScore: number | null;
                        /**
                         * Lifecycle
                         * @description The lifecycle status of the API
                         */
                        lifecycle: {
                            /**
                             * @description The lifecycle status
                             * @example deprecated
                             * @example sunset
                             * @example retired
                             * @enum {string}
                             */
                            status: "active" | "deprecated" | "sunset" | "retired";
                            /**
                             * @description The version of the API
                             * @example 1.0.0
                             */
                            version: string;
                            /**
                             * Format: date
                             * @description The date from which the lifecycle status is/has been deprecated, sunset or retired.
                             * @example 2025-01-15
                             */
                            from?: string | null;
                        };
                    }[];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    retreiveApi: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The unique identifier for an API
                         * @example dicF0B3HR
                         */
                        readonly id: string;
                        /**
                         * Contact
                         * @description Contact details
                         */
                        contact: {
                            /**
                             * Format: email
                             * @description The email address of the contact
                             * @example developer.overheid@geonovum.nl
                             */
                            email: string;
                            /**
                             * @description The name of the contact
                             * @example Developer Overheid
                             */
                            name: string;
                            /**
                             * Format: uri
                             * @description The URL of the contact
                             * @example https://developer.overheid.nl
                             */
                            url: string;
                        };
                        /**
                         * @description The title of the API
                         * @example API register API v1
                         */
                        title: string;
                        /**
                         * @description The description of the API
                         * @example This is version 1 of the API register. This description can also contain Markdown.
                         */
                        description: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /**
                         * @description The ADR score of the API
                         * @example 85
                         */
                        adrScore: number | null;
                        /**
                         * Lifecycle
                         * @description The lifecycle status of the API
                         */
                        lifecycle: {
                            /**
                             * @description The lifecycle status
                             * @example deprecated
                             * @example sunset
                             * @example retired
                             * @enum {string}
                             */
                            status: "active" | "deprecated" | "sunset" | "retired";
                            /**
                             * @description The version of the API
                             * @example 1.0.0
                             */
                            version: string;
                            /**
                             * Format: date
                             * @description The date from which the lifecycle status is/has been deprecated, sunset or retired.
                             * @example 2025-01-15
                             */
                            from?: string | null;
                        };
                    } & {
                        /**
                         * Format: uri
                         * @description The URL of the OAS document
                         * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
                         */
                        oasUrl: string | null;
                        /** @description The authentication methods supported by the API */
                        auth: string[];
                        /**
                         * Format: uri
                         * @description The URL to the documentation of the API
                         * @example https://developer.overheid.nl/kennisbank/
                         */
                        docsUrl: string | null;
                        servers: unknown;
                    };
                };
            };
            /** @description Resource does not exist */
            404: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    updateApi: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * OAS Url
                     * Format: uri
                     * @description The URL of the OAS document
                     * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
                     */
                    oasUrl: string;
                    /**
                     * Organisation URI
                     * Format: uri
                     * @description The unique identifier for an organisation
                     * @example https://developer.overheid.nl
                     */
                    organisationUri: string;
                    /**
                     * Contact
                     * @description Contact details
                     */
                    contact?: {
                        /**
                         * Format: email
                         * @description The email address of the contact
                         * @example developer.overheid@geonovum.nl
                         */
                        email: string;
                        /**
                         * @description The name of the contact
                         * @example Developer Overheid
                         */
                        name: string;
                        /**
                         * Format: uri
                         * @description The URL of the contact
                         * @example https://developer.overheid.nl
                         */
                        url: string;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The unique identifier for an API
                         * @example dicF0B3HR
                         */
                        readonly id: string;
                        /**
                         * Contact
                         * @description Contact details
                         */
                        contact: {
                            /**
                             * Format: email
                             * @description The email address of the contact
                             * @example developer.overheid@geonovum.nl
                             */
                            email: string;
                            /**
                             * @description The name of the contact
                             * @example Developer Overheid
                             */
                            name: string;
                            /**
                             * Format: uri
                             * @description The URL of the contact
                             * @example https://developer.overheid.nl
                             */
                            url: string;
                        };
                        /**
                         * @description The title of the API
                         * @example API register API v1
                         */
                        title: string;
                        /**
                         * @description The description of the API
                         * @example This is version 1 of the API register. This description can also contain Markdown.
                         */
                        description: string;
                        /**
                         * Organisation summary
                         * @description An organisation from the catalog
                         */
                        organisation: {
                            /**
                             * Organisation URI
                             * Format: uri
                             * @description The unique identifier for an organisation
                             * @example https://developer.overheid.nl
                             */
                            uri: string;
                            /**
                             * @description The label of the organisation
                             * @example developer.overheid.nl
                             */
                            label: string;
                        };
                        /**
                         * @description The ADR score of the API
                         * @example 85
                         */
                        adrScore: number | null;
                        /**
                         * Lifecycle
                         * @description The lifecycle status of the API
                         */
                        lifecycle: {
                            /**
                             * @description The lifecycle status
                             * @example deprecated
                             * @example sunset
                             * @example retired
                             * @enum {string}
                             */
                            status: "active" | "deprecated" | "sunset" | "retired";
                            /**
                             * @description The version of the API
                             * @example 1.0.0
                             */
                            version: string;
                            /**
                             * Format: date
                             * @description The date from which the lifecycle status is/has been deprecated, sunset or retired.
                             * @example 2025-01-15
                             */
                            from?: string | null;
                        };
                    } & {
                        /**
                         * Format: uri
                         * @description The URL of the OAS document
                         * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
                         */
                        oasUrl: string | null;
                        /** @description The authentication methods supported by the API */
                        auth: string[];
                        /**
                         * Format: uri
                         * @description The URL to the documentation of the API
                         * @example https://developer.overheid.nl/kennisbank/
                         */
                        docsUrl: string | null;
                        servers: unknown;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
            /** @description Resource does not exist */
            404: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    getPostman: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["404"];
        };
    };
    getOasVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
                /** @description OAS version and format, e.g. 3.0.json or 3.1.yaml. */
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    /** @description Returned OAS version (e.g. 3.0 or 3.1). */
                    "OAS-Version"?: string;
                    /** @description Source of the OAS document. */
                    "OAS-Source"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "application/yaml": string;
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
        };
    };
    getOpenApiSpecification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    listOrganisations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Organisation URI
                         * Format: uri
                         * @description The unique identifier for an organisation
                         * @example https://developer.overheid.nl
                         */
                        uri: string;
                        /**
                         * @description The label of the organisation
                         * @example developer.overheid.nl
                         */
                        label: string;
                    }[];
                };
            };
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Organisation URI
                     * Format: uri
                     * @description The unique identifier for an organisation
                     * @example https://developer.overheid.nl
                     */
                    uri: string;
                    /**
                     * @description The label of the organisation
                     * @example developer.overheid.nl
                     */
                    label: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Organisation URI
                         * Format: uri
                         * @description The unique identifier for an organisation
                         * @example https://developer.overheid.nl
                         */
                        uri: string;
                        /**
                         * @description The label of the organisation
                         * @example developer.overheid.nl
                         */
                        label: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    /** @description Semver of this API */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * @description The HTTP status code generated by the origin server for this occurrence of the problem
                         * @example 400
                         */
                        status: number;
                        /**
                         * @description A short, human-readable summary of the problem type
                         * @example Request validation failed
                         */
                        title: string;
                        errors?: {
                            /**
                             * @description Location of the error (e.g., body, query, header)
                             * @enum {string}
                             */
                            in: "body" | "query";
                            /**
                             * @description Location in the document where the error occurred (JSON Pointer)
                             * @example #/foo[0]/bar
                             */
                            location: string;
                            /**
                             * @description A code representing the type of error
                             * @example date.format
                             */
                            code: string;
                            /**
                             * @description A detailed message describing the error
                             * @example must be ISO 8601
                             */
                            detail: string;
                        }[];
                    };
                };
            };
        };
    };
    getAdoptionApis: {
        parameters: {
            query?: {
                adrVersion?: string;
                apiIds?: string | null;
                compliant?: boolean | null;
                endDate?: string;
                organisation?: string | null;
                page?: number;
                perPage?: number;
                ruleCodes?: string | null;
                startDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsAdoptionApis"];
                };
            };
            400: components["responses"]["400"];
        };
    };
    getAdoptionRules: {
        parameters: {
            query?: {
                adrVersion?: string;
                apiIds?: string | null;
                endDate?: string;
                organisation?: string | null;
                ruleCodes?: string | null;
                severity?: string | null;
                startDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsAdoptionRules"];
                };
            };
            400: components["responses"]["400"];
        };
    };
    getAdoptionSummary: {
        parameters: {
            query?: {
                adrVersion?: string;
                apiIds?: string | null;
                endDate?: string;
                organisation?: string | null;
                startDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsAdoptionSummary"];
                };
            };
            400: components["responses"]["400"];
        };
    };
    getAdoptionTimeline: {
        parameters: {
            query?: {
                adrVersion?: string;
                apiIds?: string | null;
                endDate?: string;
                granularity?: string;
                organisation?: string | null;
                ruleCodes?: string | null;
                startDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsAdoptionTimeline"];
                };
            };
            400: components["responses"]["400"];
        };
    };
}
export enum ApiPaths {
    listApis = "/apis",
    createApi = "/apis",
    searchApis = "/apis/_search",
    retreiveApi = "/apis/{id}",
    updateApi = "/apis/{id}",
    getPostman = "/apis/{id}/postman",
    getOasVersion = "/apis/{id}/oas/{version}",
    getOpenApiSpecification = "/openapi.json",
    listOrganisations = "/organisations",
    createOrganisation = "/organisations",
    getAdoptionApis = "/statistics/apis",
    getAdoptionRules = "/statistics/rules",
    getAdoptionSummary = "/statistics/summary",
    getAdoptionTimeline = "/statistics/timeline"
}
