/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List APIs
         * @description Returns a list of APIs included in the register. Supports the same filter query parameters as the filters endpoint and combines them with the optional q search term.
         */
        get: operations["listApis"];
        put?: never;
        /**
         * Register API
         * @description Registers a new API in the register from its OpenAPI document.
         */
        post: operations["createApi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/_search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search APIs
         * @deprecated
         * @description Deprecated. Use GET /apis with the q query parameter and filters instead.
         */
        get: operations["searchApis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API filters
         * @description Returns all available API filter options with counts. Counts are calculated using the active filters and optional q search term from the request.
         */
        get: operations["listApiFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lint-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all lint results
         * @description Returns all stored lint results for registered APIs.
         */
        get: operations["listLintResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get API by id
         * @description Returns a single API by id.
         */
        get: operations["retreiveApi"];
        /**
         * Update API
         * @description Updates an existing API by id. When no OAS document is supplied, only lifecycle fields can be changed.
         */
        put: operations["updateApi"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}/feed.rss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get API RSS feed
         * @description Returns an RSS 2.0 feed with content changes for a single API. Feed items are created for ADR-score changes, lifecycle changes, OpenAPI document hash changes, and OpenAPI documents that become unavailable during the daily refresh job.
         */
        get: operations["getApiFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}/postman": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Download Postman collection
         * @description Returns the generated Postman JSON.
         */
        get: operations["getPostman"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}/oas/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
                /** @description OAS version and format, e.g. 3.0.json or 3.1.yaml. */
                version: string;
            };
            cookie?: never;
        };
        /**
         * Download OAS document
         * @description Returns the OAS 3.0 or 3.1 specification in JSON or YAML.
         */
        get: operations["getOasVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI documentation
         * @description Download the OpenAPI specification for this API.
         */
        get: operations["getOpenApiSpecification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organisations
         * @description Returns a list of organisations included in the register.
         */
        get: operations["listOrganisations"];
        put?: never;
        /**
         * Create organisation
         * @description Create a new organisation.
         */
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Contact
         * @description Contact details
         */
        Contact: {
            /**
             * Format: email
             * @description The email address of the contact
             * @example developer.overheid@geonovum.nl
             */
            email: string;
            /**
             * @description The name of the contact
             * @example Developer Overheid
             */
            name: string;
            /**
             * Format: uri
             * @description The URL of the contact
             * @example https://developer.overheid.nl
             */
            url: string;
        };
        /**
         * Organisation summary
         * @description An organisation from the catalog
         */
        OrganisationSummary: {
            /**
             * Organisation URI
             * Format: uri
             * @description The unique identifier for an organisation
             * @example https://developer.overheid.nl
             */
            uri: string;
            /**
             * @description The label of the organisation
             * @example developer.overheid.nl
             */
            label: string;
        };
        /**
         * Lifecycle
         * @description The lifecycle status of the API
         */
        Lifecycle: {
            /**
             * @description The lifecycle status
             * @example deprecated
             * @example sunset
             * @example retired
             * @enum {string}
             */
            status: "active" | "deprecated" | "sunset" | "retired";
            /**
             * @description The version of the API
             * @example 1.0.0
             */
            version: string;
            /**
             * Format: date
             * @description The date from which the API is will be/has been deprecated.
             * @example 2025-10-10
             */
            deprecated?: string;
            /**
             * Format: date
             * @description The date from which the API will be/has been taken offline.
             * @example 2027-11-11
             */
            sunset?: string;
        };
        Server: {
            /**
             * Format: uri
             * @description The URL of the server
             * @example https://api.developer.overheid.nl/api-register/v1
             */
            url: string;
            /**
             * @description A description of the server
             * @example Production server
             */
            description: string;
        };
        /**
         * API
         * @description An API from the catalog
         */
        ApiSummary: {
            /**
             * @description The unique identifier for an API
             * @example dicF0B3HR
             */
            readonly id: string;
            contact: components["schemas"]["Contact"];
            /**
             * @description The title of the API
             * @example API register API v1
             */
            title: string;
            /**
             * @description The description of the API
             * @example This is version 1 of the API register. This description can also contain Markdown.
             */
            description: string;
            /** @description The summary of the API */
            summary: string | null;
            organisation: components["schemas"]["OrganisationSummary"];
            /**
             * @description The ADR score of the API
             * @example 85
             */
            adrScore: number | null;
            lifecycle: components["schemas"]["Lifecycle"];
        };
        /**
         * API
         * @description An API from the catalog
         */
        ApiDetail: components["schemas"]["ApiSummary"] & {
            /**
             * Format: uri
             * @description The URL of the OAS document
             * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
             */
            oasUrl: string | null;
            /** @description The authentication methods supported by the API */
            auth: string[];
            /**
             * Format: uri
             * @description The URL to the documentation of the API
             * @example https://developer.overheid.nl/kennisbank/
             */
            docsUrl: string | null;
            servers: components["schemas"]["Server"][];
        };
        /** @description Single selectable filter option with the count for the current filter context. */
        FilterOption: {
            /** @description The query parameter value for this option. */
            value: string;
            /** @description Human-readable label for this option. */
            label: string;
            /** @description Optional explanation of this option. */
            description?: string | null;
            /** @description Number of APIs matching this option, given the other active filters. */
            count: number;
            /** @description Whether this option is currently selected in the request. */
            selected: boolean;
        };
        /** @description Filter metadata group for API list facets. */
        FilterGroup: {
            /**
             * @description Query parameter key for this filter.
             * @example status
             * @example oasVersion
             * @example adrScore
             * @example auth
             */
            key: string;
            /** @description Human-readable filter label. */
            label: string;
            /** @description Description of what this filter controls. */
            description: string;
            /**
             * @description UI control type for the filter.
             * @enum {string}
             */
            type: "multi-select" | "single-select" | "toggle" | "date";
            /** @description Current value for non-option filters. */
            value?: unknown;
            /** @description Count for toggle or date filters. */
            count?: number;
            options?: components["schemas"]["FilterOption"][];
        };
        /**
         * API (JSON-LD)
         * @description JSON-LD representation of an API as a dcat:DataService. Returned when Accept: application/ld+json is requested on /apis/{id}.
         */
        ApiDetailJsonLd: {
            /** @description Inline JSON-LD context defining the dcat, dct and vcard prefixes plus type-coercions for IRI-valued properties. */
            "@context": Record<string, never>;
            /** @enum {string} */
            "@type": "dcat:DataService";
            /**
             * @example [
             *       "https://spec.openapis.org/oas"
             *     ]
             */
            "dct:conformsTo": string[];
            /** @example dicF0B3HR */
            "dct:identifier": string;
            "dct:title": string;
            "dct:description"?: string;
            /**
             * Format: uri
             * @description URL of the OpenAPI document describing this DataService.
             */
            "dcat:endpointDescription"?: string;
            "dcat:contactPoint": {
                "vcard:fn": string;
                /**
                 * Format: uri
                 * @description mailto: IRI.
                 */
                "vcard:hasEmail"?: string;
                /** Format: uri */
                "vcard:hasURL"?: string;
            };
            /**
             * Format: uri
             * @description IRI of the publishing organisation.
             */
            "dct:publisher"?: string;
        };
        /**
         * API Input
         * @description Input for registering an API from its OpenAPI or Arazzo document
         */
        ApiInput: {
            /**
             * OAS Url
             * Format: uri
             * @description The URL of the OAS document
             * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
             */
            oasUrl?: string;
            /**
             * OAS Body
             * @description The inline OAS document in JSON or YAML format
             */
            oasBody?: string;
            /**
             * Arazzo Url
             * Format: uri
             * @description The URL of the Arazzo document
             */
            arazzoUrl?: string;
            /**
             * Arazzo Body
             * @description The inline Arazzo document in JSON or YAML format
             */
            arazzoBody?: string;
            /**
             * Organisation URI
             * Format: uri
             * @description The unique identifier for an organisation
             * @example https://developer.overheid.nl
             */
            organisationUri: string;
            contact?: components["schemas"]["Contact"];
        } | unknown | unknown;
        /**
         * API Update Input
         * @description Input for updating an API from its OpenAPI document or by overriding lifecycle dates
         */
        ApiUpdateInput: {
            /**
             * OAS Url
             * Format: uri
             * @description The URL of the OAS document
             * @example https://api.developer.overheid.nl/api-register/v1/openapi.json
             */
            oasUrl?: string;
            /**
             * OAS Body
             * @description The inline OAS document in JSON or YAML format
             */
            oasBody?: string;
            /**
             * Arazzo Url
             * Format: uri
             * @description The URL of the Arazzo document
             */
            arazzoUrl?: string;
            /**
             * Arazzo Body
             * @description The inline Arazzo document in JSON or YAML format
             */
            arazzoBody?: string;
            /**
             * Organisation URI
             * Format: uri
             * @description The unique identifier for an organisation
             * @example https://developer.overheid.nl
             */
            organisationUri: string;
            contact?: components["schemas"]["Contact"];
            /**
             * Format: date
             * @description Manual override for the sunset date (YYYY-MM-DD). Send null to clear the value.
             * @example 2027-11-11
             * @example null
             */
            sunset?: string | null;
            /**
             * Format: date
             * @description Manual override for the deprecated date (YYYY-MM-DD). Send null to clear the value.
             * @example 2025-10-10
             * @example null
             */
            deprecated?: string | null;
        } | unknown | unknown | unknown | unknown;
        /**
         * Problem JSON
         * @description Problem JSON schema representing errors and status code
         */
        ProblemJson: {
            /**
             * @description The HTTP status code generated by the origin server for this occurrence of the problem
             * @example 400
             */
            status: number;
            /**
             * @description A short, human-readable summary of the problem type
             * @example Request validation failed
             */
            title: string;
            errors?: {
                /**
                 * @description Location of the error (e.g., body, query, header)
                 * @enum {string}
                 */
                in: "body" | "query";
                /**
                 * @description Location in the document where the error occurred (JSON Pointer)
                 * @example #/foo[0]/bar
                 */
                location: string;
                /**
                 * @description A code representing the type of error
                 * @example date.format
                 */
                code: string;
                /**
                 * @description A detailed message describing the error
                 * @example must be ISO 8601
                 */
                detail: string;
            }[];
        };
    };
    responses: {
        /** @description Bad request */
        400: {
            headers: {
                "API-Version": components["headers"]["ApiVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemJson"];
            };
        };
        /** @description Resource does not exist */
        404: {
            headers: {
                "API-Version": components["headers"]["ApiVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemJson"];
            };
        };
    };
    parameters: {
        /** @description Page number (1-based). */
        Page: number;
        /** @description Number of results per page. */
        PerPage: number;
        /** @description Search term to combine with API filters. Matches API title. */
        Search: string;
        /** @description Filter on organisation URI. */
        Organisation: string;
        /** @description Comma-separated list of API IDs. */
        Ids: string;
        /** @description Filter on lifecycle status. Repeat the parameter or use comma-separated values. */
        Status: ("active" | "deprecated" | "sunset" | "retired")[];
        /** @description Filter on the API version from the OAS info.version field. Repeat the parameter or use comma-separated values. */
        OasVersion: string[];
        /** @description Filter on stored ADR score. Use exact scores or 'unknown' for APIs without a stored score. */
        AdrScore: string[];
        /** @description Filter on the authentication/security type derived from the OAS security definition. */
        Auth: ("none" | "api_key" | "oauth2" | "openid" | "bearer" | "basic" | "http" | "unknown")[];
    };
    requestBodies: never;
    headers: {
        /** @description Semver of this API */
        ApiVersion: string;
        /** @description Links to the previous, next, last or first pages */
        Link: string;
        /** @description Total number of items available */
        TotalCount: number;
        /** @description Current page number */
        CurrentPage: number;
        /** @description Number of items per page */
        PerPage: number;
        /** @description Total number of pages available */
        TotalPages: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApis: {
        parameters: {
            query?: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
                /** @description Search term to combine with API filters. Matches API title. */
                q?: components["parameters"]["Search"];
                /** @description Filter on organisation URI. */
                organisation?: components["parameters"]["Organisation"];
                /** @description Comma-separated list of API IDs. */
                ids?: components["parameters"]["Ids"];
                /** @description Filter on lifecycle status. Repeat the parameter or use comma-separated values. */
                status?: components["parameters"]["Status"];
                /** @description Filter on the API version from the OAS info.version field. Repeat the parameter or use comma-separated values. */
                oasVersion?: components["parameters"]["OasVersion"];
                /** @description Filter on stored ADR score. Use exact scores or 'unknown' for APIs without a stored score. */
                adrScore?: components["parameters"]["AdrScore"];
                /** @description Filter on the authentication/security type derived from the OAS security definition. */
                auth?: components["parameters"]["Auth"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSummary"][];
                };
            };
            400: components["responses"]["400"];
        };
    };
    createApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSummary"];
                };
            };
            400: components["responses"]["400"];
        };
    };
    searchApis: {
        parameters: {
            query: {
                /** @description Page number (1-based). */
                page?: components["parameters"]["Page"];
                /** @description Number of results per page. */
                perPage?: components["parameters"]["PerPage"];
                /** @description Filter on organisation URI. */
                organisation?: components["parameters"]["Organisation"];
                /** @description Search term. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    Link: components["headers"]["Link"];
                    "Total-Count": components["headers"]["TotalCount"];
                    "Current-Page": components["headers"]["CurrentPage"];
                    "Per-Page": components["headers"]["PerPage"];
                    "Total-Pages": components["headers"]["TotalPages"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSummary"][];
                };
            };
            400: components["responses"]["400"];
        };
    };
    listApiFilters: {
        parameters: {
            query?: {
                /** @description Search term to combine with API filters. Matches API title. */
                q?: components["parameters"]["Search"];
                /** @description Filter on organisation URI. */
                organisation?: components["parameters"]["Organisation"];
                /** @description Comma-separated list of API IDs. */
                ids?: components["parameters"]["Ids"];
                /** @description Filter on lifecycle status. Repeat the parameter or use comma-separated values. */
                status?: components["parameters"]["Status"];
                /** @description Filter on the API version from the OAS info.version field. Repeat the parameter or use comma-separated values. */
                oasVersion?: components["parameters"]["OasVersion"];
                /** @description Filter on stored ADR score. Use exact scores or 'unknown' for APIs without a stored score. */
                adrScore?: components["parameters"]["AdrScore"];
                /** @description Filter on the authentication/security type derived from the OAS security definition. */
                auth?: components["parameters"]["Auth"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterGroup"][];
                };
            };
            400: components["responses"]["400"];
        };
    };
    listLintResults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        apiId: string;
                        successes: boolean;
                        failures: number;
                        warnings: number;
                        /** Format: date-time */
                        createdAt: string;
                        messages?: {
                            id: string;
                            lintResultId: string;
                            line: number;
                            column: number;
                            severity: string;
                            code: string;
                            rulesetVersion?: string;
                            /** Format: date-time */
                            createdAt: string;
                            infos?: {
                                id: string;
                                lintMessageId: string;
                                message: string;
                                path: string;
                            }[];
                        }[];
                    }[];
                };
            };
            400: components["responses"]["400"];
        };
    };
    retreiveApi: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiDetail"];
                    "application/ld+json": components["schemas"]["ApiDetailJsonLd"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    updateApi: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiUpdateInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSummary"];
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
        };
    };
    getApiFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example <?xml version="1.0" encoding="UTF-8"?>
                     *     <rss version="2.0">
                     *       <channel>
                     *         <title>Wijzigingen voor Voorbeeld API</title>
                     *         <link>https://apis.developer.overheid.nl/apis/api-1</link>
                     *         <description>RSS feed met inhoudelijke wijzigingen voor Voorbeeld API.</description>
                     *         <language>nl</language>
                     *       </channel>
                     *     </rss>
                     */
                    "application/rss+xml": string;
                };
            };
            404: components["responses"]["404"];
        };
    };
    getPostman: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["404"];
        };
    };
    getOasVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the resource. */
                id: string;
                /** @description OAS version and format, e.g. 3.0.json or 3.1.yaml. */
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    /** @description Returned OAS version (e.g. 3.0 or 3.1). */
                    "OAS-Version"?: string;
                    /** @description Source of the OAS document. */
                    "OAS-Source"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "application/yaml": string;
                };
            };
            400: components["responses"]["400"];
            404: components["responses"]["404"];
        };
    };
    getOpenApiSpecification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    listOrganisations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSummary"][];
                };
            };
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OrganisationSummary"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "API-Version": components["headers"]["ApiVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationSummary"];
                };
            };
            400: components["responses"]["400"];
        };
    };
}
export enum ApiPaths {
    listApis = "/apis",
    createApi = "/apis",
    searchApis = "/apis/_search",
    listApiFilters = "/apis/filters",
    listLintResults = "/lint-results",
    retreiveApi = "/apis/{id}",
    updateApi = "/apis/{id}",
    getApiFeed = "/apis/{id}/feed.rss",
    getPostman = "/apis/{id}/postman",
    getOasVersion = "/apis/{id}/oas/{version}",
    getOpenApiSpecification = "/openapi.json",
    listOrganisations = "/organisations",
    createOrganisation = "/organisations"
}
