/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/arazzo/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arazzo Markdown (POST)
         * @description Genereert alleen de Markdown-uitvoer van een Arazzo specificatie. Body: { oasUrl|oasBody }
         */
        post: operations["arazzoMarkdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/arazzo/mermaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arazzo Mermaid (POST)
         * @description Genereert alleen de Mermaid flowchart van een Arazzo specificatie. Body: { oasUrl|oasBody }
         */
        post: operations["arazzoMermaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Maak client (POST)
         * @description Maak een client aan via de admin API. Body bevat Email.
         */
        post: operations["untrustClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oas/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Converteer OpenAPI 3.0/3.1
         * @description Converteert OpenAPI naar de laatst ondersteunde versie (standaard 3.1). Meegegeven targetVersion (3.0 of 3.1) bepaalt het doel. Body: { oasUrl } of { oasBody } (stringified JSON of YAML).
         */
        post: operations["convertOAS"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oas/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bundle OpenAPI
         * @description Bundelt een OpenAPI specificatie en lost externe verwijzingen op. Body: { oasUrl } of { oasBody }.
         */
        post: operations["bundleOAS"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oas/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate OpenAPI
         * @description Genereert een boilerplate OpenAPI specificatie op basis van JSON-invoer. Body: { oasUrl } of { oasBody } (stringified JSON).
         */
        post: operations["generateOAS"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oas/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate OpenAPI (POST)
         * @description Valideert een OpenAPI specificatie met de DON ADR ruleset. Standaard wordt ruleset 2.1 gebruikt; geef targetVersion "2.0" of "2.1" mee om een versie te kiezen. Body: { oasUrl } of { oasBody } (stringified JSON of YAML).
         */
        post: operations["validatorOpenAPIPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oas/postman": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Maak Postman-collectie (POST)
         * @description Converteert OpenAPI naar Postman Collection JSON. Body: { oasUrl } of { oasBody } (stringified JSON of YAML).
         */
        post: operations["createPostmanCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "oasUrl": "oasUrl",
         *       "oasBody": "oasBody",
         *       "targetVersion": "3.1"
         *     }
         */
        OASInput: {
            oasBody?: string;
            oasUrl?: string;
            /** @description Doelversie. Voor conversie: 3.0 of 3.1. Voor validatie: 2.0 of 2.1. */
            targetVersion?: string;
        };
        /**
         * @example {
         *       "apiKey": "apiKey"
         *     }
         */
        ModelsKeycloakClientResult: {
            apiKey?: string;
        };
        /**
         * @example {
         *       "severity": "severity",
         *       "createdAt": "2000-01-23T04:56:07.000Z",
         *       "code": "code",
         *       "id": "id",
         *       "infos": [
         *         {
         *           "path": "path",
         *           "lintMessageId": "lintMessageId",
         *           "id": "id",
         *           "message": "message"
         *         },
         *         {
         *           "path": "path",
         *           "lintMessageId": "lintMessageId",
         *           "id": "id",
         *           "message": "message"
         *         }
         *       ]
         *     }
         */
        ModelsLintMessage: {
            code?: string;
            /** Format: date-time */
            createdAt?: string;
            id?: string;
            infos?: components["schemas"]["ModelsLintMessageInfo"][];
            severity?: string;
        };
        /**
         * @example {
         *       "path": "path",
         *       "lintMessageId": "lintMessageId",
         *       "id": "id",
         *       "message": "message"
         *     }
         */
        ModelsLintMessageInfo: {
            id?: string;
            lintMessageId?: string;
            message?: string;
            path?: string;
        };
        /**
         * @example {
         *       "createdAt": "2000-01-23T04:56:07.000Z",
         *       "score": 6,
         *       "failures": 0,
         *       "successes": true,
         *       "messages": [
         *         {
         *           "severity": "severity",
         *           "createdAt": "2000-01-23T04:56:07.000Z",
         *           "code": "code",
         *           "id": "id",
         *           "infos": [
         *             {
         *               "path": "path",
         *               "lintMessageId": "lintMessageId",
         *               "id": "id",
         *               "message": "message"
         *             },
         *             {
         *               "path": "path",
         *               "lintMessageId": "lintMessageId",
         *               "id": "id",
         *               "message": "message"
         *             }
         *           ]
         *         },
         *         {
         *           "severity": "severity",
         *           "createdAt": "2000-01-23T04:56:07.000Z",
         *           "code": "code",
         *           "id": "id",
         *           "infos": [
         *             {
         *               "path": "path",
         *               "lintMessageId": "lintMessageId",
         *               "id": "id",
         *               "message": "message"
         *             },
         *             {
         *               "path": "path",
         *               "lintMessageId": "lintMessageId",
         *               "id": "id",
         *               "message": "message"
         *             }
         *           ]
         *         }
         *       ],
         *       "id": "id",
         *       "apiId": "apiId"
         *     }
         */
        ModelsLintResult: {
            apiId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int32 */
            failures?: number;
            id?: string;
            messages?: components["schemas"]["ModelsLintMessage"][];
            /** Format: int32 */
            score?: number;
            successes?: boolean;
        };
        /**
         * @example {
         *       "email": "email"
         *     }
         */
        UntrustClientInput: {
            email?: string;
        };
    };
    responses: {
        /** @description Resource does not exist */
        404: {
            headers: {
                "API-Version": headers["API-Version"];
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description De API-versie van de response */
        "API-Version": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    arazzoMarkdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OASInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    arazzoMermaid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OASInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    untrustClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UntrustClientInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsKeycloakClientResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    convertOAS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OASInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bundleOAS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OASInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generateOAS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OASInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validatorOpenAPIPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OASInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsLintResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPostmanCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OASInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description De API-versie van de response */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
